### ISSUE TITLE
Overlay Text or Image on top of panel

### ISSUE THREAD

**Issue by philipjacobs** [CSS-Tricks/MovingBoxes#108]
I would like to overlay and image and some text over the image that shows up in the panel.
I borrowed code from another project I'm working on but having difficulties making this work.
Here's an example of what I would like to do.
http://livedemo00.template-help.com/wt_38428/index.html
The three boxes with the _specials_ is what I would like to have scrolling on this page.
I'm not sure how to show code here so I'll just copy and paste what I currently have.
HTML

``` html
<div id="wrapper">
  <ul id="slider">
   <div class="price">from
     <div class="red_font">$589<sup>.99</sup></div>
   </div>
   </li>
     <img src="../../RV-Rental-2000-Georgie-Boy-Pursuit-Turnbull/thumbnails/Georgie-Boy-Pursuit-IMG_3148.jpg" alt="picture">
     <h2>2000 Georgie Boy - Pursuit</h2>
     <p>Add a short exerpt here... ahref="http://flickr.com/photos/justbcuz/112479862/">more</a></p>
   </li>
   </div>
  </ul>
```

CSS

``` css
.red_font{
    color:#B52007;
    font-weight: bold;
    font-size: 16px;
}
.price{
    position:absolute;
    right:1137px;
    bottom:49px;
    width:85px;
    height:58px;
    background:url(../images/price.png) no-repeat;
    font-size: 14px;
    color:#fff;
    text-align:right;
    padding-top: 20px;
    padding-right: 5px;
    padding-bottom: 10;
    padding-left: 0;
    vertical-align: bottom;
    z-index: 2;
}
```

JS

``` javascript
$(function(){
  $('#slider').movingBoxes({
    /* width and panelWidth options deprecated, but still work to keep the plugin backwards compatible
    width: 500,*/
    panelWidth   : 0.21,
    fixedHeight  : true,
    startPanel   : 1,      // start with this panel
    wrap         : true,  // if true, the panel will infinitely loop
    buildNav     : false,   // if true, navigation links will be added
    reducedSize  : 1,
    navFormatter : function(){ return "&#9679;"; } // function which returns the navigation text for each panel
  });
});
```
