### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by gokhanartuk** [CSS-Tricks/MovingBoxes#130]
Hi 

Having problem about using in rlt supported pages. Actually When I add dir="rtl" to page nothin is working correctly. Are u planing to have rtl support in soon?

**Comment by Mottie** [comment]
Hi @gokhanartuk!

I don't think anyone is actively maintaining this plugin, but if you want it to work when a page is set for RTL, add the following css to fix it ([demo](http://jsfiddle.net/Mottie/acV4n/746/)):

``` css
.movingBoxes {
    direction: ltr;
    unicode-bidi: bidi-override;
}
```

Switching the wrapper to LTR shouldn't effect the content in the panels... also, set the `startPanel` to show the last panel.
