### ISSUE TITLE
Dimming the right & left images.

### ISSUE THREAD

**Issue by kaushal123** [CSS-Tricks/MovingBoxes#38]
It is grate slider.
I have already given opacity to right & left images but how can it be darken to a light black? so middle image looks brighter.
Any Help Please?
Thanks.

**Comment by Mottie** [comment]
You could add some css to lower the opacity of the side images, like this ([demo](http://jsfiddle.net/Mottie/r6yWC/359/)):

``` css
.mb-panel {
    opacity: 0.5;
    filter: alpha(opacity=50);   
}
.mb-panel.current {
    opacity: 1;
    filter: alpha(opacity=100);
}
```
