### ISSUE TITLE
Opacity

### ISSUE THREAD

**Issue by superyarik** [CSS-Tricks/MovingBoxes#69]
i think good idea is to add opacity(for not active items) option, for using in .animation

**Comment by Mottie** [comment]
Maybe try this bit of css ([demo](http://jsfiddle.net/Mottie/jMXx3/721/)):

``` css
.mb-panel:not(.current) {
    opacity: 0.5;
    filter: alpha(opacity=50);
}
```

**Comment by superyarik** [comment]
yes, it is work, but opacity appear after clicking next/prev button, not nice.

**Comment by Mottie** [comment]
Ok, try some css3 transitions then ([demo](http://jsfiddle.net/Mottie/jMXx3/722/)):

``` css
.mb-panel:not(.current) {
    opacity: 0.5;
    filter: alpha(opacity=50);
    -webkit-transition: opacity 1s ease-out;  /* Saf3.2+, Chrome */
       -moz-transition: opacity 1s ease-out;  /* FF4+ */
        -ms-transition: opacity 1s ease-out;  /* IE10 */
         -o-transition: opacity 1s ease-out;  /* Opera 10.5+ */
            transition: opacity 1s ease-out;
}
```
