### ISSUE TITLE
Smoothing transition of centered content

### ISSUE THREAD

**Issue by chorn99** [CSS-Tricks/MovingBoxes#76]
I'm not completely knowledgable in JavaScript so I need help smoothing out a transition.

My basic problem is that I am not changing the size of the content (image) but just having the slides decrease in width. I was able to get the image to be centered both in the current and non-current slides using CSS, but because the css rule of "current" does not apply to the slide until after the transition, the image looks like it is jumping to the center of the enlarged slide.

Is there a way to use JavaScript to animate this?

I've created a demo here: http://jsfiddle.net/GRvum/1/

**Comment by Mottie** [comment]
You could add some css3 transitions to smooth it out - [demo](http://jsfiddle.net/Mottie/GRvum/2/)

CSS

``` css
#slider { width: 600px; }
#slider li { width: 300px; }

.mb-inside * {
    max-width: none;
}

/*** Inside the panel ***/
.mb-inside {
    overflow: hidden;
    padding: 0;
}

.mb-inside > div.image {
    display: block;
    width: 300px;
    height: 221px;
    margin-left: -75px;
    position:relative;
}

.mb-panel .reveal img {
    margin-left: 0;
    width: 300px;
    margin-left: 0;
    -webkit-animation: reveal .7s ease;
    -moz-animation: reveal .7s ease;
    -ms-animation: reveal .7s ease;
    -o-animation: reveal .7s ease;
    animation: reveal .7s ease;
}

@-webkit-keyframes reveal {
    0%   { margin-left: -75px; }
    100% { margin-left: 0; }
}
@-moz-keyframes reveal {
    0%   { margin-left: -75px; }
    100% { margin-left: 0; }
}
@-ms-keyframes reveal {
    0%   { margin-left: -75px; }
    100% { margin-left: 0; }
}
@keyframes reveal {
    0%   { margin-left: -75px; }
    100% { margin-left: 0; }
}
```

Script

``` javascript
$('#slider').movingBoxes({
    startPanel   : 1,      
    wrap         : false,   
    fixedHeight  : true,
    reducedSize  : .5,
    speed        : 200,
    buildNav     : true,   
    navFormatter : function(){ return "&#9679;"; },

    // **** Callbacks ****
    // e = event, slider = MovingBoxes Object, tar = current panel #
    // callback when MovingBoxes has completed initialization
    initialized: function(e, slider, tar){
        // set starting panel
        slider.$panels.eq(tar-1).find('.mb-inside').addClass('reveal');
    },
    // callback before any animation occurs
    beforeAnimation: function(e, slider, tar){
        slider.$el.find('.reveal').removeClass('reveal');
        slider.$panels.eq(tar-1).find('.mb-inside').addClass('reveal');
    }                     

});​
```
