### ISSUE TITLE
Using Objects in Boxes does not allow scrolling

### ISSUE THREAD

**Issue by RyanEricW** [CSS-Tricks/MovingBoxes#91]
http://rfiles.org/_in/index.php?idx=videos

Normally you can click on "boxes" either to the left or right, and it will scroll without activating the content. While using <object> code provided by youtube, it triggers the video without scrolling to that slide. Is there a way I can fix this?

Thanks

**Comment by Mottie** [comment]
I think the easiest solution might be to give the non-current panel videos a negative z-index so that when you click, you're actually clicking on the div inside of the panel, the following would be all the extra css you would need - [demo](http://jsfiddle.net/Mottie/acV4n/50/)

``` css
.mb-inside object, .mb-inside embed {
    position: relative;
    z-index: -1;
}
.current .mb-inside object, .current .mb-inside embed {
    position: relative;
    z-index: 1;
}
```

Note: I set the `reducedSize` option to `1` to keep all of the panels the same size, because if I remember correctly, Firefox will reload/reset the video every time it gets resized.
